### ISSUE TITLE
Update OEMetadata - Key Description

### ISSUE THREAD

**Issue by chrwm** [OpenEnergyPlatform/oemetadata#107]
The naming conventions for oem-key 15.6.1.1 and oem-key 15.2 have to be updated with regards to using the OEMetadata with the OEP.
When creating tables on the OEP with OEMetadata via the API, `.` and `-` are not allowed in both keys. The same applies when creating a table via the OEP Wizzard.

I suggest changing the descriptions:

**oem-key 15.6.1.1**

_Current:_ 
A name for the entire data package. To comply with the data package standard it must consist of only lowercase alphanumeric character plus ".", "-" and "_". It may not start with a number. In a database, this will be the name of the table within the schema containing it. The name usually corresponds to the file name (minus the file-extension) of the data file describing the resource.

_New:_ 
A name for the entire data package. The name must consist of only lowercase alphanumeric characters or underscore. It must not start with a number or underscore. In a database, this will be the name of the table within the schema containing it. The name can correspond to the file name (minus the file-extension) of the data file describing the resource, if it complies with the naming convention above. Name also contains information about the shema on the OEP, use "." to seperate shema from table name.

**oem-key 15.2**

_Current:_ 
The name of the field. 

_New:_
The name of the field. The name must consist of only lowercase alphanumeric characters or underscore. It must not start with a number or underscore.

If you agree, I'll go ahead and change the [description ](https://github.com/OpenEnergyPlatform/oemetadata/blob/develop/metadata/latest/metadata_key_description.md)on the dev branch. @jh-RLI

**Comment by jh-RLI** [comment]
I think the text at 15.2 should be at 15.6.1.1 and the other way around :D But i agree with your proposal.

**Comment by chrwm** [comment]
Yes you're right, ups.

Alright, I'll implement then:

oem-key 15.2

Current:
A name for the entire data package. To comply with the data package standard it must consist of only lowercase alphanumeric character plus ".", "-" and "_". It may not start with a number. In a database, this will be the name of the table within the schema containing it. The name usually corresponds to the file name (minus the file-extension) of the data file describing the resource.

New:
A name for the entire data package. The name must consist of only lowercase alphanumeric characters or underscore. It must not start with a number or underscore. In a database, this will be the name of the table within the schema containing it. The name can correspond to the file name (minus the file-extension) of the data file describing the resource, if it complies with the naming convention above. Name also contains information about the shema on the OEP, use "." to seperate shema from table name.

oem-key 15.6.1.1

Current:
The name of the field.

New:
The name of the field. The name must consist of only lowercase alphanumeric characters or underscore. It must not start with a number or underscore.

**Comment by chrwm** [comment]
Closed with [29a2f69](https://github.com/OpenEnergyPlatform/oemetadata/commit/29a2f695321d9d9a1f2351f468a27124af1d3e9b)
