### ISSUE TITLE
Improve repository

### ISSUE THREAD

**Issue by jh-RLI** [OpenEnergyPlatform/oemetadata#120]
- [x] Finish and close all open PR
- [x] Rename `master` branch to `production`
- [x] Close stale branches
- [x] Review issues and add to [GitHub project ](https://github.com/OpenEnergyPlatform/oemetadata/projects/3)
- [x] Add Issue and PR templates #115
- [x] CITATION.cff
- [x] Code of Conduct
- [x] CONTRIBUTING.md
- [x] LICENSE.txt
- [x] USERS.cff

**Comment by Ludee** [comment]
Implement #122

**Comment by Ludee** [comment]
Branch renamed!
