### ISSUE TITLE
Add tests to prevent duplicated schema entries.

### ISSUE THREAD

**Issue by jh-RLI** [OpenEnergyPlatform/oemetadata#125]
Thank you for finding all the redundancies and little errors! Maybe it's possible to write a test for duplicates in future.

_Originally posted by @christian-rli in https://github.com/OpenEnergyPlatform/oemetadata/issues/117#issuecomment-1467709172_

**Comment by jh-RLI** [comment]
@christian-rli can you tell me a bit more about the test you suggested. As far as I understand, the test would look for duplicate entries in schmea.json?

**Comment by christian-rli** [comment]
There isn't more to tell. You just described the suggested test in its entirety :)

**Comment by jh-RLI** [comment]
Ah okay, just any duplocate (like key names). I thought you had an example as I didn't follow the discussion before :)

**Comment by christian-rli** [comment]
I looked into the commits again. the naming suggested duplicate ("redundant") fields. I seems like there weren't actually any, but it's a useful test to be implemented anyway (and an easy one, in case someone needs to learn how to write tests).
