### ISSUE TITLE
Update the license fields according to frictionless specifications

### ISSUE THREAD

**Issue by Ludee** [OpenEnergyPlatform/oemetadata#127]
## Description of the issue

Latest version has two additional (custom) fields for the license: `attribution` and `instruction`.
They are very useful but not conform with frictionless.

The documentation has specific keys for this:
```JSON
"licenses" : [{
    "name": "CC-BY-4.0",
    "path": "https://creativecommons.org/licenses/by/4.0/",
    "title": "Creative Commons Attribution 4.0"
  }],
  "copyrightNotice": "© The State of Queensland 1995–2017",
  "copyrightStatement": "https://www.qld.gov.au/legal/copyright",
  "attributionText": "Science, Information Technology and Innovation, Queensland Government, Coastal Data System – Near real time wave data, licensed under Creative Commons Attribution 4.0 sourced on 26 December 2017",
  ```

Source: https://frictionlessdata.io/blog/2018/03/27/applying-licenses/#provide-additional-license-information

## Ideas of solution

- Rename key `attribution` to `copyrightNotice`
- Add terms `copyrightStatement` to a link that proves the data is licensed

Discuss:
- `attributionText` is not conform with TASL. Would be a copy of other keys depending on the licenses.
- `instruction` is a nice-to-have feature that briefly states the rights and obligation. Do we keep it?

## Workflow checklist
- [x] I am aware of the workflow in [CONTRIBUTING.md](https://github.com/OpenEnergyPlatform/oemetadata/blob/develop/CONTRIBUTING.md)

**Comment by jh-RLI** [comment]
As far as I understand, we don't have to use the exact naming from the frictionless example. They used, this specific names as they are proposed by this [guide of the open data institute](https://www.theodi.org/article/publishers-guide-to-the-open-data-rights-statement-vocabulary/). We could also keep our naming, as these are[ additional fields](https://specs.frictionlessdata.io/data-package/#descriptor) that are not part of the frictionless specification.
