### ISSUE TITLE
OMI bug regarding translation

### ISSUE THREAD

**Issue by hedwiglieselotte** [OpenEnergyPlatform/oemetadata#129]
## Description of the issue

These are the bugs I found while using OMI to review metadata in DigiPlan.

## Steps to Reproduce
0. I created a metadata file
1. omi translate -f oep-v1.5 -t oep-v1.5 

## Ideas of solution

Describe possible ideas for solution and evaluate advantages and disadvantages.

## Context and Environment
* Version used:  0.1.2
* Operating system: Linux
* Environment setup and (python) version: 3.10

## Workflow checklist
- [ ] I am aware of the workflow in [CONTRIBUTING.md](https://github.com/rl-institut/super-repo/blob/develop/CONTRIBUTING.md)

**Comment by hedwiglieselotte** [comment]
Exception 1: omi.dialects.base.parser.ParserException: invalid value for date: 2023-28-03

**Comment by hedwiglieselotte** [comment]
Exception 2:
``` bash
  File "/home/local/RL-INSTITUT/hedwig.bartels/miniconda3/envs/Metadaten/lib/python3.10/site-packages/omi/dialects/oep/parser.py", line 65, in parse_date_or_none
    raise ParserException(f"invalid type for date: {type(x)}")
omi.dialects.base.parser.ParserException: invalid type for date: <class 'list'>
```

**Comment by jh-RLI** [comment]
Thanks for this report, omi was fully reworked and its new version will be released soon. The translation functionality works differently and now depends on the  json schema. This is not relevant anymore :)
