### ISSUE TITLE
Context field in metadata/<version>/ always links to oemetadata/develop/metadata/latest/context.json

### ISSUE THREAD

**Issue by jh-RLI** [OpenEnergyPlatform/oemetadata#135]
## Description of the issue

In all example.json files for each release we link to the context.json file that is in latest: https://raw.githubusercontent.com/OpenEnergyPlatform/oemetadata/develop/metadata/latest/context.json

## Steps to Reproduce
https://github.com/OpenEnergyPlatform/oemetadata/blob/cc4ebffbcec096f642c30432c70afc7f2e6fbdd2/metadata/v160/example.json#L390

## Ideas of solution

We should link to the context file that is related to the current release.

## Context and Environment
* Version used: 
* Operating system: 
* Environment setup and (python) version: 

## Workflow checklist
- [x] I am aware of the workflow in [CONTRIBUTING.md](https://github.com/rl-institut/super-repo/blob/develop/CONTRIBUTING.md)

**Comment by chrwm** [comment]
> We should link to the context file that is related to the current release.

For the released versions this could be changed.
For future releases, the link should be changed in a commit during the release, as the OEMetadata version folder is currently only created with the release if I'm not mistaken.

**Comment by jh-RLI** [comment]
- [ ] Fix URL for existing releases
- [ ] Add task to release prozedure ... Update context field url to release source

**Comment by Ludee** [comment]
The field `@context` has been included in version 151. 

Looking at the older version the links to `schema.json` are broken until version 150.
