### ISSUE TITLE
Evaluate if `spatial` field is fit for ontological use

### ISSUE THREAD

**Issue by chrwm** [OpenEnergyPlatform/oemetadata#136]
## Description of the issue

In the [oeo-dev meeting 63](https://etherpad.wikimedia.org/p/oeo-dev-63#L40) geographical regions and their incorporation into the OEO were discussed.

- [ ] check if current metadata can represent annotation solution from oeo-dev meeting

```
"spatial": {
        "location": null,
        "extent": "europe",
        "resolution": "100 m"
```

## Ideas of solution

Describe possible ideas for solution and evaluate advantages and disadvantages.

## Workflow checklist
- [x] I am aware of the workflow in [CONTRIBUTING.md](https://github.com/OpenEnergyPlatform/oemetadata/blob/develop/CONTRIBUTING.md)

**Comment by Ludee** [comment]
This has been solved with an refactoring of the spatial section.
