### ISSUE TITLE
Add the possibility to include a path to contributors

### ISSUE THREAD

**Issue by areleu** [OpenEnergyPlatform/oemetadata#137]
## Description of the issue

The current state of the contributor section could be expanded for better traceability. I think one valuable change could be to be able to add identifiers to the person. One example is obviously an ORCID but not limited to it, one could also the link to the person public corporate profile. 

## Ideas of solution

Add a new list field called identifiers so one could pack multiple ids. Alternatively add a path field to the contributors which should at least add one field, in this case I would encouraage people to use ORCID.

## Workflow checklist
- [x] I am aware of the workflow in [CONTRIBUTING.md](https://github.com/OpenEnergyPlatform/oemetadata/blob/develop/CONTRIBUTING.md)

**Comment by jh-RLI** [comment]
Good idea! We will discuss it.
