### ISSUE TITLE
Add embargo information to the metadata

### ISSUE THREAD

**Issue by jh-RLI** [OpenEnergyPlatform/oemetadata#140]
## Description of the issue

We are currently in the process of implementing the “EmbargoArea” on the OEP website. It makes sense to add this information to the Oemetadata when a table with embargo has been published.

## Ideas of solution

- Introduction of a new field in the metadata "UnterEmbagroUntil".
- This field is set automatically as soon as the user selects the embargo time (during the publication of the data). It is also usabale outside the oep ecosystem of course.
- 
Note: In future, users will be able to select the embargo option when uploading the data to the OEP. The data will then be available in "model_draf", but will not be publicly visible. The exact embargo time will only be selected when the user publishes the data via the OEP user interface or the API (and moves it from "model_draft" to another topic).
- Possibly another field like "isEmbargo" should also be added

## Workflow checklist
- [ ] I am aware of the workflow in [CONTRIBUTING.md](https://github.com/OpenEnergyPlatform/oemetadata/blob/develop/CONTRIBUTING.md)

**Comment by Ludee** [comment]
https://en.wikipedia.org/wiki/Embargo_(academic_publishing)
> In [academic publishing](https://en.wikipedia.org/wiki/Academic_publishing), an embargo is a period during which access to academic journals is not allowed to users who have not paid for access (or have access through their institution).
Various types exist:

    A 'moving wall' is a fixed period of months or years.
    A fixed date is a particular time point that does not change.
    A current year (or other period) is setting a time point on Jan. 1 of the current year, so that all material earlier than that is available. Although fixed during the year, it will change each year.

"activeEmbargo": "true" / "false"
"EmbargoStartDate": "2024-10-10"
"embargoEndDate": "2025-10-10" (max. 1 year from "EmbargoStartDate")

will set the:
"activeEmbargo": "false"
"publicationDate": "2025-10-10",

**Comment by jh-RLI** [comment]
The Helmholtz kernel information profile https://oceanrep.geomar.de/id/eprint/57942/7/2022-12_HMC-Paper_2_PID-KIP_V1.pdf suggests the key “UnterEmbagroUntil”. Maybe we should add it too, this was mentioned by @carstenhoyerklick   

As an alternative, which requires more effort, we could collect terms that need mapping later. Or use the context file to describe the fields in detail, link them to other resources and also give the fields alternative labels. I'm not sure if this is possible, but it would help us become interoperable with other standards.

**Comment by Ludee** [comment]
Using the _underEmbargoUntil_ is a quite simple and easy solution.
Besides me not really liking the key name you also suggested to have an boolean field that can be used by the OEP to implement the feature. Looking from the perspective of a published dataset that was embargoed it will be useful to know that and how long the embargo period was. Simply using _start_ and _end_ covers all possible combinations and gathers all necessary information in one place. This adds it an own section:

```
"embargoPeriod": {
        "start": "2024-10-10,
        "end": "2025-10-10",
        "activeEmbargo": "true"
    },
```

**Comment by carstenhoyerklick** [comment]
I like the solution with a start and end. The active Embargo may need to be changed once the end date passes. I would not rely on the uses to update it in time. But within Moss and databus, we probably can implement a Mod which scans the embargo information once a day and updates the status.

**Comment by jh-RLI** [comment]
> Using the _underEmbargoUntil_ is a quite simple and easy solution. Besides me not really liking the key name you also suggested to have a boolean field that can be used by the OEP to implement the feature. Looking from the perspective of a published dataset that was embargoed it will be useful to know that and how long the embargo period was. Simply using _start_ and _end_ covers all possible combinations and gathers all necessary information in one place. This adds it an own section:
> 
> ```
> "embargoPeriod": {
>         "start": "2024-10-10,
>         "end": "2025-10-10",
>         "activeEmbargo": "true"
>     },
> ```

I like it too, I just wanted to pick up on the previous thoughts. Also, a mod that can check and automatically update the embargo status sounds good. But I think we need to implement revisions for metadata in the OEP for that. I'm not 100% familiar with how Databus/Moss handles things in the backend, but in discussions earlier this year we talked about synchronizing the life cycles for metadata in OEP and Databus. On the OEP, there is currently only one version of metadata per datatable, and if someone edits it, there is no system to track the changes. In this case, the metadata would be in a different state than in the metadata registered on the Databus (i assume), which would lead to inconsistencies. If the Databus also edits the metadata, conflicts easily arise when we want to merge both metadata documents. There are other solutions than implementing revisions for metadata in the OEP, but we would need to discuss this again.

**Comment by carstenhoyerklick** [comment]
I don't if we can add Jan und Sebastian here. The current version of databus/moss has edit features for the metadata and also traces changes to the metadata. So we could use databus/moss as source of truth but we need to find a way to propagate the changes to the OEP.

**Comment by Ludee** [comment]
The connection to the Databus is another discussion and does belong in another issue.

```JSON
"embargoPeriod": {
        "start": "2024-10-11",
        "end": "2025-01-01",
        "isActive": "true"
    },
```
