### ISSUE TITLE
MetaIssue: OEMetadata v2.0

### ISSUE THREAD

**Issue by jh-RLI** [OpenEnergyPlatform/oemetadata#144]
## Description of the issue

We are currently working on the next release of our oemeta data specification. This topic will be used to collect tasks and reference commits aimed at general setup setups.

Add mappings to DCAT-AP and Dublin Core.

## Ideas of solution

Resolve issues in project https://github.com/orgs/OpenEnergyPlatform/projects/41

## Workflow checklist
- [x] I am aware of the workflow in [CONTRIBUTING.md](https://github.com/OpenEnergyPlatform/oemetadata/blob/develop/CONTRIBUTING.md)

**Comment by Ludee** [comment]
Here are some notes and a timeline for the upcoming release.

**Notes:**
- Older versions need to be updated when we rename the master branch. `schema.json` and `example.json` and documentation
