### ISSUE TITLE
Use more explicit types in the json schema instead of just "string".

### ISSUE THREAD

**Issue by jh-RLI** [OpenEnergyPlatform/oemetadata#146]
## Description of the issue

The [JSON schema spec](https://json-schema.org/understanding-json-schema/reference/string#built-in-formats) allows some build in additional types. 

## Ideas of solution

Since we are currently doing a rewrite of omi checking sting types against python types is not how we want to do this anymore. Using the tooling around json schema is a better solution. 

We need to update the type field for each element in the json schema if the value can be described as something else than "string".

## Workflow checklist
- [x] I am aware of the workflow in [CONTRIBUTING.md](https://github.com/OpenEnergyPlatform/oemetadata/blob/develop/CONTRIBUTING.md)

**Comment by jh-RLI** [comment]
FYI
@henhuy @christian-rli

**Comment by Ludee** [comment]
I just checked the list and most formats are already implemented. Needed options are:

- "date": _2018-11-13_
- "date-time": _2018-11-13T20:20:39+00:00_
- "uri": A universal resource identifier (URI), according to [RFC3986](http://tools.ietf.org/html/rfc3986).
