### ISSUE TITLE
Consider adapting to Datapackage v2.0

### ISSUE THREAD

**Issue by areleu** [OpenEnergyPlatform/oemetadata#148]
## Description of the issue

The folks from frictionless data have been doing a good job improving and extending their [data package specification](https://datapackage.org/overview/changelog/). One important new feature is that it by default accepts URIs in their fields https://datapackage.org/standard/table-schema/#rdfType which could be used to replace our isAbout field.

If we comply with this specification our need of tool development could be made ligther becasuse we would be able to use the tools they develop for that spec.

## Ideas of solution

Make releaase 2.0 datapackage 2.0 compatible.

## Workflow checklist
- [ ] I am aware of the workflow in [CONTRIBUTING.md](https://github.com/OpenEnergyPlatform/oemetadata/blob/develop/CONTRIBUTING.md)

**Comment by jh-RLI** [comment]
Ah, they've finally published it :) Thank you for letting us know. We are currently working on releasing an oemetadate 2.0 version and there is a lot to consider. This week there will be a first draft version in the development branch. On this basis, we can incorporate the suggestions from the datapackaege 2.0 specification. The final release of oemetadata 2.0 will take some time, as such a big change should mean that most users are happy with the result and a possible 3.0 version will not be necessary or only optional for a long time.

**Comment by Ludee** [comment]
I am checking the changelog in order to identify which changes are relevant for us.
I collect the changes in a Pad: https://etherpad.wikimedia.org/p/oemetadata2.0

**Comment by Ludee** [comment]
As far as I see, only the _profile_ has been removed.

"profile": "tabular-data-resource", -> "type": "table"
https://datapackage.org/standard/data-resource/#type
