### ISSUE TITLE
Change repo/package/module namespace to oemetadata

### ISSUE THREAD

**Issue by 4lm** [OpenEnergyPlatform/oemetadata#15]
1. The OEP related repos [now](https://github.com/OpenEnergyPlatform/metadata/commit/5c15dbd122618714ca2f5f45273d1e3669d7cbfe) use the wording "Open Energy Family" instead of "OpenEngeryPlatform", because of this the namespace should change on PyPI from "oep-" to "oef-" (which seems to be available: https://pypi.org/search/?q=oef). 

2. The module name "metadata" is very generic and IMO should be changed to "oef_metadata", to avoid possible module name conflicts in the future. Because of this I also would change the repo name to "oef-metadata" (conventions: Git(hub) repo and (PyPI) package names separated by "-" and the module names by "_").

What do you think?

**Comment by 4lm** [comment]
@Ludee had IMO a good idea we could change the namespace like in oedialect to "oe", which would result in "oemetadata", so we would not have to decide between "oef-" or "oep-" and we would be consistent with "oedialect" the only other OEP/OEF package released on PyPI.

What do you think?

**Comment by Bachibouzouk** [comment]
I am for the "oe" namespacing :)

**Comment by jh-RLI** [comment]
@Ludee Have we agreed on "oemetadata"?

**Comment by Ludee** [comment]
It seems like it! Can you do it?
Please have a look at the other repos as well.

**Comment by Ludee** [comment]
> @Ludee I haven't done that yet, but I'm gonna figure it out!

Perfekt, please research (try) and document:
https://github.com/OpenEnergyPlatform/organisation/wiki/OEP-Organisation
https://github.com/OpenEnergyPlatform/organisation/issues/33

**Comment by jh-RLI** [comment]
I want to rename the repo to "oemetadata" and update de package name on PyPI. Do you see any major problems with that? @Ludee @christian-rli @MGlauer

**Comment by jh-RLI** [comment]
Done. I will close this. We have to figure out, how the new URL is handled before merging into the master branch.
