### ISSUE TITLE
Create context.json for new oemetadata structure

### ISSUE THREAD

**Issue by jh-RLI** [OpenEnergyPlatform/oemetadata#153]
## Description of the issue

We need a context.json file for the updated oemetadata v2 structure. 

## Ideas of solution

TBD

## Workflow checklist
- [x] I am aware of the workflow in [CONTRIBUTING.md](https://github.com/OpenEnergyPlatform/oemetadata/blob/develop/CONTRIBUTING.md)

FYI: @Ludee

**Comment by Ludee** [comment]
I copied the **context.json** from version 1.6.0.
I sorted the imported ontologies and harmonised with the imports of the oeo.
Only a few keys are already included. This is a large follow-up to find suitable terms in existing ontologies or adding them to the oeo.
