### ISSUE TITLE
Do we need fixed/static links for the json schemas?

### ISSUE THREAD

**Issue by 4lm** [OpenEnergyPlatform/oemetadata#16]
Hi all,

I need input! What do you think, should we communicate fixed/static links of our json files for external linking? Maybe communicated in the readme?

Context: https://github.com/OpenEnergyPlatform/omi/pull/26#issuecomment-561234429

IMO a git repo is not an archive, we should be able to refactor all code and only assume coupling to external libraries via code delivery mechanisms (like PyPI) or (if one really wants to do that) as plain code copies.

But what to do, if we want to communicate specific, fixed assets (like json files) to the outside world? IMO links to tagged verision could be one way. For the json files of the release v1.0.1 this would be:

https://raw.githubusercontent.com/OpenEnergyPlatform/metadata/v1.0.1/metadata/v130/schema.json
https://raw.githubusercontent.com/OpenEnergyPlatform/metadata/v1.0.1/metadata/v130/template.json
https://raw.githubusercontent.com/OpenEnergyPlatform/metadata/v1.0.1/metadata/v130/example.json

https://raw.githubusercontent.com/OpenEnergyPlatform/metadata/v1.0.1/metadata/v140/schema.json
https://raw.githubusercontent.com/OpenEnergyPlatform/metadata/v1.0.1/metadata/v140/template.json
https://raw.githubusercontent.com/OpenEnergyPlatform/metadata/v1.0.1/metadata/v140/example.json

For multiple releases IMO this would be a communication mess. So, if yes we want to communicate fixed links, it should be only the hard-links of the latest release, which is not super convenient, because one would have to commit the urls to the readme before they exist, because there is no release at that stage. Does anyone have a better idea?

**Comment by Bachibouzouk** [comment]
> because one would have to commit the urls to the readme before they exist, because there is no release at that stage. Does anyone have a better idea?

I don't see it as a problem, because we know the version number in before making the release, and the readme of `master` is only updated once the release branch is merged :)
