### ISSUE TITLE
Feedback: the term resources is required by frictionless but not in line with other popular specifications

### ISSUE THREAD

**Issue by jh-RLI** [OpenEnergyPlatform/oemetadata#173]
## Description of the issue

The **"resources"** key is fixed by frictionless, but is not in line with other standards. DCAT-AP uses distributions. This conflict can not be mitigated without adding a tool that can translate this key for the given use case.

## Ideas of solution

Consider how to handle this as the databus uses distributions.

## Workflow checklist
- [x] I am aware of the workflow in [CONTRIBUTING.md](https://github.com/OpenEnergyPlatform/oemetadata/blob/develop/CONTRIBUTING.md)

**Comment by Ludee** [comment]
This is an important information. Since the current version is based on frictionless, we should stick to it to be compatible.
We definitely need a proper DCAT-AP version and a working translator in OMI.
