### ISSUE TITLE
Slight diffs between oemetadata v2 and frictionless auto generated data schema keys 

### ISSUE THREAD

**Issue by jh-RLI** [OpenEnergyPlatform/oemetadata#174]
## Description of the issue

Describing the data is one of the main challenges when working with the oemetadata. As the OEP will add the schema for any table on the OEP to the oemetadata automatically, the main effort here is to define the structure initially. Many users will start of some JSON or CSV formatted data. Frictionless provides tools that can automatically generate a schema for the file formats. 

Here is an example CSV and the resulting generated schema:

[test2.csv](https://github.com/user-attachments/files/17463887/test2.csv)
[schema.json](https://github.com/user-attachments/files/17463889/schema.json)

After you installed frictionless you can generate the schema using the following command in a terminal where the related python env is activated:

`pip install frictionless`
`frictionless describe test2.csv --json > schema.json  `

As you can see, frictionless adds additional keys that we currently do not have. But the oemetadata validation will not fail if they are present.

## Ideas of solution

Consider if we should add the keys that are part of the automated schema generation.

## Workflow checklist
- [x] I am aware of the workflow in [CONTRIBUTING.md](https://github.com/OpenEnergyPlatform/oemetadata/blob/develop/CONTRIBUTING.md)

**Comment by Ludee** [comment]
I think the difference is only the two keys:

-   "scheme": "file",
-   "mediatype": "text/csv",

We already have the field _"format": "csv", "format": "PostgreSQL"_,
There is no advantage in having these optional keys.

**Comment by jh-RLI** [comment]
I agree, but we should mention that in the documentation. I just wonder where ... after testing the frictionless functionality to generate the schema, this would best fit best into the tutorial about creating oemetdata. If the user got a csv already, using frictionless to generate the data model schema would be good practice. Still, the datatype that are part of the generated schema are not always aligned with the database data types.
