### ISSUE TITLE
GitHub Tags are not very useful

### ISSUE THREAD

**Issue by Ludee** [OpenEnergyPlatform/oemetadata#208]
## Description of the issue

The tags are outdated

## Ideas of solution

Copy from super-repo

https://github.com/OpenEnergyPlatform/oemetadata/labels

## Workflow checklist
- [x] I am aware of the workflow in [CONTRIBUTING.md](https://github.com/OpenEnergyPlatform/oemetadata/blob/develop/CONTRIBUTING.md)

**Comment by Ludee** [comment]
New labels are grouped by:

- **part** (backend 🧱, community 🌍, documentation 📖, github :octocat:)
- **type** (bug 🐛, enhancement ⚙️, feature 🛠, question ❓, release 🚀)
- **priority** (low 🦥, high ⚡, critical 🔥)
- **status** (active 🚧, blocked 🛑, completed ✔️)
- **resolution** (duplicate 🐾, invalid ❌, released 🎉, wontfix ⛔)
- **other** (good first issue 🌱, help wanted 🙋)

**Comment by Ludee** [comment]
The colours of the tags are bad. It looks too messy. A nice colour theme would be nice @bmlancien

**Comment by Ludee** [comment]
![grafik](https://github.com/user-attachments/assets/e9d75f8a-136e-4c00-b30e-530cfd0480cf)

**Comment by bmlancien** [comment]
Here are 2 ideas of palettes. I included how people with normal vision see them and then how most color blind users might see them (I only included the most common types of color blindness):

Palette 1: 
- Use of sequential palettes for Part, Type, Resolution and Other categories
- Priority and Status keep qualitative palettes
- I think it is well suited for users with normal vision but not really for color blind users

![GitHub Labels - 1](https://github.com/user-attachments/assets/e4a81808-8833-48cf-be88-c0aabc069668)

Palette 2: 
- Use of same colors for each category (Part, Type, Resolution and Other), so there are no differentiations between labels inside the same category
- Priority and Status use qualitative palettes
- Probably better suited for most of users with color blindness than palette 1

![GitHub Labels - 2](https://github.com/user-attachments/assets/6e2331f5-8a89-4d4a-ab6d-93de49ee2f04)

**Comment by Ludee** [comment]
WOW, that looks so much better. I will try them and decide which one will be implemented.
Thank you 🥰

**Comment by Ludee** [comment]
I like the Palette 2 normal version. Smooth colours and good readability.

![grafik](https://github.com/user-attachments/assets/05c15676-2b50-4338-974b-5669751535b1)

**Comment by bmlancien** [comment]
Good that you liked them!
I think the second version looks good, indeed :)

The colors for the status are all the same. Is this what you wanted?

**Comment by Ludee** [comment]
I updated the status like you suggested and now it is perfect!
This should be used in ever collaborative GitHub repo 🤩

**Comment by bmlancien** [comment]
Cool that you like it 😍

**Comment by stap-m** [comment]
Cool! Feel free to suggest and apply new tags for the oeo repo @Ludee 😉
