### ISSUE TITLE
Restrict version naming in paths, module names etc. to SemVer major and minor but not patch

### ISSUE THREAD

**Issue by 4lm** [OpenEnergyPlatform/oemetadata#21]
Hi all,

as discussed in https://github.com/OpenEnergyPlatform/omi/pull/26#issuecomment-562096417 I would like to use restrict version naming in paths, module names etc. to SemVer major and minor but not patch. Refresh on what SemVer versioning means: [link](https://semver.org/)

- this would mean for module paths for example `v130/*` to `v1.3/*`
- this would mean for imports for  for example `V130` to `V1_3`

This will give us the possibility to link (URL) to major and minor versions of our schemas, without breaking third party code in the future or making refactors concerning the version number necessary, if there is a patch (backwards compatible change) for a schema rolling in.

What do you think?

**Comment by Ludee** [comment]
This should definitely be taken into account. I think we just messed this up in the current minor version. @jh-RLI

**Comment by jh-RLI** [comment]
As far as I understand, there is no consensus on this topic yet. I don't understand github as a platform to store different historically grown versions either, but right now this is our solution. If we want to maintain a new structure we have to do it in a bigger revision. Currently, I think it's best to store all versions explicitly.

**Comment by Ludee** [comment]
Very satisfying to close such an old issue. Kudos to @4lm ♥
