### ISSUE TITLE
Template script needs improvement

### ISSUE THREAD

**Issue by Ludee** [OpenEnergyPlatform/oemetadata#216]
## Description of the issue

The template generation results in an error.
Reason is the `boundingBox` field. Should be _[0,0,0,0]_ instead of _[0]_.

## Workflow checklist
- [x] I am aware of the workflow in [CONTRIBUTING.md](https://github.com/OpenEnergyPlatform/oemetadata/blob/develop/CONTRIBUTING.md)

**Comment by jh-RLI** [comment]
OffTopic but related: We are missing a better example for the table resources schema. The schema.json only provides a single example. We have a nice example available in the previous versions. There is only the nullable missing. We could add some extra code to extend the example and add it to the example.json.
