### ISSUE TITLE
Collect license files in licenses directory?

### ISSUE THREAD

**Issue by jh-RLI** [OpenEnergyPlatform/oemetadata#224]
## Description of the issue

I would argue to put the reuse? license files inside a directory to keep the resource files most present. But this is a more subjective opinion.

## Workflow checklist
- [x] I am aware of the workflow in [CONTRIBUTING.md](https://github.com/OpenEnergyPlatform/oemetadata/blob/develop/CONTRIBUTING.md)

**Comment by Ludee** [comment]
As discussed the .json files will be annotated in REUSE.toml instead of with .license.
