### ISSUE TITLE
Enhance spatial fields to enhance compatibility to RDF

### ISSUE THREAD

**Issue by jh-RLI** [OpenEnergyPlatform/oemetadata#233]
## Description of the issue

To be able to better map properties to ontology terms, enhance structure of the spatial object. So far this is only a suggestion to enhance the metadata further can be included in later versions also.

The background is that location and extent names seem duplicated in meaning.

## Ideas of solution

```
"spatial" : {
    "location": {
        "@id": "https://www.wikidata.org/wiki/Q77077223",
        "address": "Rudower Chaussee 12, 12489 Berlin",
        "coordinates": {
            "latitude": "52.432822",
            "longitude": "13.5351004"
        }
    },
    "area": {
        "shape": "POLYGON((13.08825 52.33859, 13.76104 52.33859, 13.76104 52.6754, 13.08825 52.6754, 13.08825 52.33859))"
    },
    "spatialResolutionInMeters": 100,
    "conformsTo": "http://www.opengis.net/def/crs/EPSG/0/4326"
}
```

## Workflow checklist
- [x] I am aware of the workflow in [CONTRIBUTING.md](https://github.com/OpenEnergyPlatform/oemetadata/blob/develop/CONTRIBUTING.md)

**Comment by Ludee** [comment]
Thanks for the suggestion. It shows that you have been working with INSPIRE lately.
Here are some general comments and concerns:
1. **Area**: Do not add geographic data in the metadata!
Adding a shape or polygon as text in the metadata is not a good idea.
If it is important, it belongs in a table and should be connected using FKeys.
If it is used to find data, the bounding box is more suitable!
There is no concept to link the data to this metadata polygon. And if there are multiple areas, it gets really messy.

2. **spatialResolutionInMeters**: Too specific
While it is nice to have everything in one resolution value, our data mostly comes with other resolution. By administrative boundary for example. Having it as "resolutionValue" + "resolutionUnit" in "m" is way more flexible!

3. **"location" and "extent"**
This needs to be described in the documentation and we need real examples to showcase the difference.

I will open a new issue for needed examples and improvements of the documentation.
