### ISSUE TITLE
Translate resources to DCAT

### ISSUE THREAD

**Issue by christian-rli** [OpenEnergyPlatform/oemetadata#25]
resources seem to define data on a different level than dcat. resources wants to describe columns of tables. dcat assigns metainfo to raw data. can the two be combined at all?

**Comment by Ludee** [comment]
I think `tabular data package` and `DCAT-AP` are not 100% compatible.
This might be a job for **OMI**?

**Comment by christian-rli** [comment]
I'm not sure what you are suggesting @Ludee . If the two aren't fully compatible, omi cannot translate between the two. There could only be an approximated representation, the value of which is questionable, because it offers the best of no worlds :)

**Comment by Ludee** [comment]
I found this draft of a mapping between DCAT-AP to schema.org from JRC:
https://ec-jrc.github.io/dcat-ap-to-schema-org/
