### ISSUE TITLE
Add metadata description

### ISSUE THREAD

**Issue by christian-rli** [OpenEnergyPlatform/oemetadata#32]

**Comment by jh-RLI** [comment]
@christian-rli @Ludee I think it would be better to put the .md file in the top level folder and not in the metadata version folder. Since all other .md files are stored there. What are your thoughts?

**Comment by jh-RLI** [comment]
I did this in PR above.

**Comment by christian-rli** [comment]
I posted the following comment in a PR that's going to be closed without merging. Jst to have it in this issue as well:

... Merging master into the feature/restructure_oem_versioning branch and subsequently reorganizing in the way we discussed might be easier than fixing the structure here. But you can choose how to proceed with the github workflow @jh-RLI . I'll approve any PR that's got the structure we discussed. 

for reference: 
foldername should be metadata, 
md file with key description in the version folder 
link in readme.md to key of latest
the folders in metadata have redundant naming. rename in the following manner:
metadata-future-release -> future
metadata-latest-release -> latest
