### ISSUE TITLE
Fix minor bugs in oemetada v1.4.0

### ISSUE THREAD

**Issue by Ludee** [OpenEnergyPlatform/oemetadata#34]
We spotted some minor bugs in the metadata template.
List and fix them ASAP.

- [x] outdated links in comment section
- [x] added info for empty list of foreign keys. See https://github.com/OpenEnergyPlatform/omi/issues/34
- [x] Platin is German -> Platinum is English ;)

**Comment by christian-rli** [comment]
@Ludee mentioned a couple bugs to me, but only orally. I remembered that there were out of date links in the comment section and fixed those. @gnn do you remember what the other one was (or whether there were any more)?

**Comment by christian-rli** [comment]
As a general comment, these changes will be done on the files in the `latest` directory and constitute version 1.4.1 for which a new folder will be created. @jh-RLI and I considered putting all version folders in a dedicated `version` directory for tidiness, but we should probably wait for that until all oefamily tools tools link to the latest directory and not specific versions.

**Comment by christian-rli** [comment]
As this issue affects no keys, but only values in the example files. I have to decided to keep the version 1.4.0 to prevent unnecessary organizational work.
