### ISSUE TITLE
Handling of unknown or non-existent values missing in metadata description

### ISSUE THREAD

**Issue by MaGering** [OpenEnergyPlatform/oemetadata#41]
In the Metadata Description (https://github.com/OpenEnergyPlatform/metadata/wiki/Metadata-Description) information is missing how you proceed if values are either 

- unknown or 
- unknown but existent or 
- not applicable

**Comment by Ludee** [comment]
And there are two documentations:
- [wiki](https://github.com/OpenEnergyPlatform/oemetadata/wiki/Metadata-Description)
- [metadata_key_description.md](https://github.com/OpenEnergyPlatform/oemetadata/blob/develop/metadata/latest/metadata_key_description.md)

In addition to this I would like to have sections in the documentation to provide better links to e.g. _sources_.

**Comment by Ludee** [comment]
We took this issue into account and added information to the `_comment` and description:

`"null": "If not applicable use: null",`
`"todo": "If a value is not yet available, use: todo"`

- unknown -> `"todo"`
- unknown but existent or -> `"todo"`
- not applicable -> `null`
