### ISSUE TITLE
Missing Connection from Metadata to Factsheets

### ISSUE THREAD

**Issue by christian-rli** [OpenEnergyPlatform/oemetadata#50]
The standard lacks an option to connect a table to scenario, model or framework factsheets. We should discuss whether there should be additional (optional) fields to make this connection.

This issue came to my mind while comparing IIASA metadata with OEM. The former focuses more on scenarios and models, while OEM sets a focus on describing the table and outsources the information to framework, model and scenario factsheets. That's good, however a connection seems to be missing. The connection could come either from the factsheets or from the data tables. Let's discuss these options and other alternatives below.

**Comment by chrwm** [comment]
It was discussed that a link between metadata and artefacts will be included in the factsheets for now and will not be part of the release v1.5.0. Hence, the discussion continues in https://github.com/OpenEnergyPlatform/oeplatform/issues/821.
