### ISSUE TITLE
Working example: datapackage from datahub.io 

### ISSUE THREAD

**Issue by jh-RLI** [OpenEnergyPlatform/oemetadata#51]
I have been looking at other working examples of frictionless data package integrations. I reviewed the "[gdp_zip.zip](https://github.com/OpenEnergyPlatform/oemetadata/files/6493564/gdp_zip.zip)" data package from datahub.io, which also uses the frictionless data convention. This issue is just about documenting that example.

I think they have some fields in the datapackage.json that we might miss, like "rowcount" or "bytes" to indicate the size of the data.

**Comment by christian-rli** [comment]
`"bytes"` would depend on how it's stored so I'd be wary of an implementation. 

`"rowcount"` could be useful, but it would have to be generated automatically on the platform. The same is true for `"type"` in a table's column description and the resource's `"path"`.

Where is a good placce to take care of this? Should OMI provide the necessary functions and the OEP will make use of them? Should it become part of the API or is it rather a script on the OEP itself that should take care of this?

**Comment by jh-RLI** [comment]
I inclued an [example datapackage](https://github.com/OpenEnergyPlatform/oedatamodel/tree/feature/improve-docs-datamodel/examples/Datapackage) in the oedatamodel repository. Parts of the oemetadata is inclued in the `datapackage.json` file.  
It was not possible to use the full oemetadata string because frictionless datapackage cannot validate all fields. Maybe this problem will be solved if the schema.json is used for validation. As soon as I have time I will test this out.

**Comment by jh-RLI** [comment]
@Ludee I think currently it is best to take the datapackage from the example above. The example still needs to be created for version 1.5.1. As it is now, however, the datapackage can be uploaded to the OEP using the oedatamodel_api. Perhaps adaptations must be made due to the new oem keys.

**Comment by Ludee** [comment]
The example table for the new version is already on the OEP:
https://openenergy-platform.org/dataedit/view/model_draft/oep_metadata_table_example_v151

I added a new column to show the OEO feature. Metadata works on the example.
