### ISSUE TITLE
README installation instructions are inconsistent

### ISSUE THREAD

**Issue by Eugenio2192** [OpenEnergyPlatform/oemetadata#57]
I tried to install the package using the instructions in the README but the package does not exist. In PyPI [this package](https://pypi.org/project/oep-metadata/ ) exists, is this supposed to be the right handle?

If yes, after the installation the example json files are not delivered, was I supposed to include them manually? if that is the case it would be nice to have the instructions written somewhere.

edit: I installed the package using the developer instructions and the import statement
`from oemetadata.v140.example import OEMETADATA_V140_EXAMPLE`
throws an error, i hat to import from metadata instead

**Comment by Ludee** [comment]
I fixed the imports in the readme. Thanks for the help!
