### ISSUE TITLE
Create an example table to showcase sound metadata

### ISSUE THREAD

**Issue by chrwm** [OpenEnergyPlatform/oemetadata#60]
An example table could be sensible to demonstrate the usefulness of metadata for data contextualisation. It could be provided as a best-practice example and linked in the documentation for new users. If implemented, new users would have a reference example and better guidance in working with metadata.

**Comment by Ludee** [comment]
While reviewing the new version 1.5.0, I also updated the examples of the older version and created examples on the OEP:

- [oep_metadata_table_example_v150](https://openenergy-platform.org/dataedit/view/model_draft/oep_metadata_table_example_v150) 
- [oep_metadata_table_example_v141](https://openenergy-platform.org/dataedit/view/model_draft/oep_metadata_table_example_v141)
- [oep_metadata_table_example_v140](https://openenergy-platform.org/dataedit/view/model_draft/oep_metadata_table_example_v140)
- [oep_metadata_table_example_v130](https://openenergy-platform.org/dataedit/view/model_draft/oep_metadata_table_example_v130)

As you suggest it makes sense to also have some real examples:

- parameter collection, e.g. [wind_turbine_library](https://openenergy-platform.org/dataedit/view/supply/wind_turbine_library)
- power plant list (geodata), e.g. [wri_global_power_plant_database](https://openenergy-platform.org/dataedit/view/supply/wri_global_power_plant_database)
- time series (weather data), e.g. [openfred_feedin_wind_2016](https://openenergy-platform.org/dataedit/view/supply/openfred_feedin_wind_2016)

**Comment by jh-RLI** [comment]
@Ludee The changes will be included in the documentation with the realease v1.5.0. The example tables are linked via the example.json. Is there any more documentation missing here, otherwise this issue will be closed as soon as the realse branch is merged.
