### ISSUE TITLE
[Open Energy Metadata Description] improvement suggestion

### ISSUE THREAD

**Issue by Bachibouzouk** [OpenEnergyPlatform/oemetadata#66]
I added a column with the suggestions of improvement of the metadata keys

|#|Key |Description |Example | Suggestion of description improvement |
|---|---|---|---|---|
| 6 | subject | Reference the topic of the resource in ontology terms | | I would provide a link to what is understood by "ontology terms", as a user I had no idea how to fill this key |
| 9 | context | Object. Contains name-value-pairs that describe the general setting, evironment or project leading to the creation or maintenance of this dataset. || I would provide under "Example" one use-case of this metadata key, and fix the typo "evironment" -> "environment"|

**Comment by Ludee** [comment]
This has been included in the release v1.5.1. Thanks for the help!
