### ISSUE TITLE
Update the ontology related fields

### ISSUE THREAD

**Issue by Ludee** [OpenEnergyPlatform/oemetadata#67]
The newly added fields for the ontology reference were tested and need to be improved.

###  **is_about**
- [x] rename to isAbout 
- [x] change value to a list

###   **value_reference** 
- [x] rename to valueReference
- [x] change value to a nested list

###   **subject**
- [x] change value to a list

**Comment by Ludee** [comment]
The update was bigger than expected.
I could extend the metadata to be able to link to the OEO.
Main results are:

#### subject
```JSON
    "subject": [
        {"name" : "energy",
        "path": "https://openenergy-platform.org/ontology/oeo/OEO_00000150"},
        {"name" : "test dataset",
        "path": "https://openenergy-platform.org/ontology/oeo/OEO_00000408"}
    ],
```

#### isAbout
```JSON
    "isAbout": [
        {"name" : "wind farm",
        "path": "https://openenergy-platform.org/ontology/oeo/OEO_00000447"}
    ],
```

#### valueReference
```JSON
    "valueReference": [
        {"value": "onshore ",
        "name": "onshore wind farm",
        "path" : "https://openenergy-platform.org/ontology/oeo/OEO_00000311"},
        {"value": "offshore ",
        "name": "offshore wind farm",
        "path" : "https://openenergy-platform.org/ontology/oeo/OEO_00000308"}
    ]
```

**Comment by steull** [comment]
Checked metadata key description and example file.
