### ISSUE TITLE
Update the JSON schema for the latest version 1.5.1

### ISSUE THREAD

**Issue by Ludee** [OpenEnergyPlatform/oemetadata#68]
Close the open PR: https://github.com/OpenEnergyPlatform/oemetadata/pull/43
Add all updated fields:

- [x] subject
- [x] isAbout
- [x] valueReference

**Comment by jh-RLI** [comment]
#43 is already adapted in #56 just kept it open in case anyone would like to leave a comment

**Comment by jh-RLI** [comment]
I will update the schema

**Comment by jh-RLI** [comment]
@Ludee I think it is not possible to let the user decide the name of the json key like in your this [example](https://github.com/OpenEnergyPlatform/oemetadata/commit/cf8b9d90331d6a1567d36d074abb6c4cb26714bc) .
```json
 "subject": [
        { 
             "name": "energy",
             "url": "https://openenergy-platform.org/ontology/oeo/OEO_00000150"},
        {
             "name": "test dataset",
             "url": "https://openenergy-platform.org/ontology/oeo/OEO_00000408"
        }
    ],
```

**Comment by jh-RLI** [comment]
Update done will test the changes later today.
