### ISSUE TITLE
Hotfixes for release v1.5.1

### ISSUE THREAD

**Issue by Ludee** [OpenEnergyPlatform/oemetadata#72]
- [x] ~~add key_description to _comment~~
- [x] format JSON #75 
- [x] fix @context in example
- [x] Update CHANGELOG.md
- [x] Update CONTRIBUTING.md
- [x] Add RELEASE_PROCEDURE.md

**Comment by jh-RLI** [comment]
format JSON is fixed by #75 @Ludee

**Comment by Ludee** [comment]
I decided against a link to the metadata description because it is already mentioned in `20.1 metadata`
