### ISSUE TITLE
Collection of bugs in v1.5.1

### ISSUE THREAD

**Issue by jh-RLI** [OpenEnergyPlatform/oemetadata#83]
- [x] template: "metadataVersion": "OEP-1.5.0", -> "metadataVersion": "oemetadata_v1.5.1",
The template.json still points to version v1.5.0. Generally we should think about how to fill these fields automatically, e.g. via a config file. This error occurs almost with each realease again. 

- [x] example: "value": "onshore ", -> "value": "onshore",
- [x] example: "value": "offshore ", -> "value": "onshore",
There are trailing spaces in the values.

- [x] metadata_key_description: 5 | language -> Add link to standard (https://tools.ietf.org/search/bcp47)

**Comment by Ludee** [comment]
Thanks for spotting this error.
Can we hotfix this or do we need to create a `v1.5.2`?

**Comment by jh-RLI** [comment]
We could create a version v1.5.11 but we cant include this in v1.5.1 because it is not possible to override existing versions on pypi (pip)

**Comment by Ludee** [comment]
I just spotted some more minor bugs in the example and key_description.
Let's use this issue to collect them for the next version.

**Comment by Ludee** [comment]
We just realised that the resource column needs the information if it is nullable or not.
This is already implemented in the Upload Wizard but not included in the metadata.

**Comment by Ludee** [comment]
I think these bugs were already included in the 1.6.0.
