### ISSUE TITLE
Metadata citation

### ISSUE THREAD

**Issue by areleu** [OpenEnergyPlatform/oemetadata#85]
What would be the recommended way to refer this metadata templates in a publication? if there is any it would be nice to have it in the README.

**Comment by Ludee** [comment]
A proper publication of the oemetadata standard has not been written yet is on my wish list.
I will add a CITATION.cff to this repo later this day.

**Comment by areleu** [comment]
Since the CITATION.cff is out there I will close there, thanks a lot!
