### ISSUE TITLE
Ontology versioning when annotating data items in oem151 

### ISSUE THREAD

**Issue by chrwm** [OpenEnergyPlatform/oemetadata#88]
During a discussion of editing an axiom in the ontology, the topic of backwards compatibility of OEO versions came up.

This is important if a sub-goal of the ontological annotation of a dataset is its long-term and unambiguous description. Without the option to specify the ontology version of annotated data items, it will not be clear what meaning and properties a data item had at the moment of annotation when OEO classes are allowed to change and conflict with its prior meaning/definition/axioms.
In other words, the ontology version is important to clearly determine which meaning and properties an OEO class and thus the data item annotated with it had at the moment of annotation.
Currently, the oem151 has no designated key to hold this information.

> Do we intend for the OEO to be backwards compatible from version to version, and if not, do we want to make that explicit?

We have in every release improvements that are not backwards compatible. That's why we do versioning.

> In the future, there might be more subtle cases. In a current multi-year project, we aim to annotate a whole input dataset as well as possible ontologically. With currently about five OEO releases a year, we need to know if we need to track the OEO version number for each annotated data item in case concept definition/axioms change and if backwards compatible is not paramount.

Annotating with the OEO (or any other ontology) should always specify the version used. Larger additions almost always lead to restructuring existing parts as this includes rethinking existing concepts,

_Originally posted by @l-emele in https://github.com/OpenEnergyPlatform/ontology/issues/1152#issuecomment-1155079831_

**Comment by chrwm** [comment]
For the annotation of a dataset in practice, this could mean either:

1. annotate the dataset only with one OEO version and save this information, for example, in the `source` key, e.g.

```
   "sources": [
        {
            "title": "Open Energy Ontology (OEO)",
            "description": "The Open Energy Ontology (OEO) to annotate this dataset is used in the specific version v.0.10.0 (https://github.com/OpenEnergyPlatform/ontology/tree/releases-v1.10.0)."
            "path": "https://github.com/OpenEnergyPlatform/ontology",
            "licenses": [
                {
                    "name": "CC0-1.0",
                    "title": "Creative Commons Zero v1.0 Universal",
                    "path": "https://creativecommons.org/publicdomain/zero/1.0/legalcode",
                    "instruction": "You are free: To Share, To Create, To Adapt",
                    "attribution": ...
                }
            ]
        },
```
This could mean that the annotation is limited to the state and amount of implemented concepts of the version. Or if the version is updated which each ontology release (in case of continuous annotations over time) one needed to check if later releases conflict with recent annotations and their intended meaning in the moment of annotation.

2. clean version could be another key in `isAbout`, `valueReference`, `subject`, e.g.
```
"isAbout": [
                            {
                                "name": "year",
                                "path": "https://openenergy-platform.org/ontology/oeo/UO_0000036"
				"version": "OEO_0.10.0"
                            }

"valueReference": [
                            {
                                "value": "onshore ",
                                "name": "onshore wind farm",
                                "path": "https://openenergy-platform.org/ontology/oeo/OEO_00000311"
				"version": "OEO_0.10.0"
                            }

"subject": [
        {
            "name": "energy",
            "path": "https://openenergy-platform.org/ontology/oeo/OEO_00000150"
	    "version": "OEO_0.10.0"
        }


```

**Comment by l-emele** [comment]
If I understood @MGlauer correctly, the OEP holds all versions of the OEO and it should be possible to reference classes of a specific version.

**Comment by l-emele** [comment]
How would the version IRI look like, in the example of https://openenergy-platform.org/ontology/oeo/OEO_00000150 ?

**Comment by l-emele** [comment]
Okay, thanks for that clarification.

**Comment by chrwm** [comment]
Thank you for the comment. 

>  That is, that definitions of established classes do not change. Changing the definition of an established class is just a fringe occurrence 

In the current development state of the OEO, there might not be as many established classes yet, as it is not used in practice that often. Thus, changing of definitions seems quite normal and accepted in the current state of development. 

> and the possible implications will have to be addressed on a case-to-case basis anyway

I think it won't be possible to address a definition change on a case-to-case basis. This is because even within the timeframe of a three-year project, to do so, one would need to document the OEO version number to become even aware of a changing definition (remembering each class definition/OEO version at the moment of annotation seems impossible). Documenting them but not in the metadata would be odd, in my opinion.

Also, for people external to the project, it's impossible to address a definition change on a case-to-case basis (e.g. years after annotation), as they don't know what was meant in the first place at the moment of annotation if the OEO version was not documented.

There is the risk that data annotated today will be misinterpreted in the future if the original meaning of a concept gets lost when its definition/axioms change with time. 

> Linking instances to versioned classes only makes it hard, if not impossible, to align them with other instances from different versions automatically

I understand the difficulty, but I can't assess it technically.

**Comment by l-emele** [comment]
I also think, that in general, that is not that a big problem. In most cases the general concept stays practically the same. We won't redefine a PV cell to a banana. If classes change, in most cases they get just a more Aristotelian definition or a definition that link to other classes that weren't there when the class was initially defined. Also changes are often simply bugfixes.
