### ISSUE TITLE
Add `profile` for geospatial data in `resources`

### ISSUE THREAD

**Issue by nesnoj** [OpenEnergyPlatform/oemetadata#90]
In the provided examples' the`profile` in the `resources` field is always filled with "tabular-data-resource" defined in the [Tabular Data Package](https://specs.frictionlessdata.io/tabular-data-package/) standard. Not sure if this can be used for geospatial data files such as geopackages as well?

I understand that currently there's no "official" spatial data package but at least there're some efforts towards a [(Geo) Spatial Data Package Specification](https://github.com/cividi/spatial-data-package). Not sure whether it is suitable or covers spatial data in general but worth to be checked.

**Comment by Ludee** [comment]
The spatial section has been refactored in order to use URI and more specific keys. Thanks for the hint.
