### ISSUE TITLE
Add profile property to the metadata schema

### ISSUE THREAD

**Issue by areleu** [OpenEnergyPlatform/oemetadata#91]
Something like this:

```
{ 

  ...
  "properties": {
    "profile" : {
      "default": "open-energy-data",
      "title": "Profile",
      "description": "The profile of this descriptor",
      "type": "string" },
  ...
  }
  ...
}
```

If we have this I could make the schema work seeamlessly with frictionless. Other alternative is to create  a descriptor called open-energy-datapackage which has this property as only additional field but I do not see the point.

**Comment by areleu** [comment]
Here is a gist with what I mean: [https://gist.github.com/areleu/96ec9102f921e96b866b16b4418f398e](https://gist.github.com/areleu/96ec9102f921e96b866b16b4418f398e)

 I just tested it with frictionless and if they integrate these two merge requests I opened the packages can be validated with little extra effort:

[https://github.com/frictionlessdata/frictionless-py/pull/1229](https://github.com/frictionlessdata/frictionless-py/pull/1229)

[https://github.com/frictionlessdata/frictionless-py/pull/1228](https://github.com/frictionlessdata/frictionless-py/pull/1228)

**Comment by areleu** [comment]
Here is a frictionless repository that you can use to test this out:

[https://github.com/areleu/frictionless-py/tree/oe_dev](https://github.com/areleu/frictionless-py/tree/oe_dev)

**Comment by areleu** [comment]
Based on this last issue I created I think including the profile is not necessary as It can be included in the data package schema.  Won't close this issue yet in case someone likes actually the idea of including the profile here

**Comment by jh-RLI** [comment]
I think it is fine to include this in the datapackage schema (we're talking about a schema for the datapackge.json?).

**Comment by areleu** [comment]
I agree, the only problem is that there is not yet a data package schema. I was writing one but haven't managed to finish it.
