### ISSUE TITLE
Implement mappings and translations for the OEMetadata

### ISSUE THREAD

**Issue by Ludee** [OpenEnergyPlatform/oemetadata#92]
There is a need for providing different formats of the string (e.g. RDF).
In addition it would be useful to be able to convert from and to other standards (DataCite, DCAT-AP...)

We don't want to develop a new tool but rather use an existing one.
This issue is a collection of existing code and methods.
Feel free to comment and improve!

- https://github.com/EUDAT-B2FIND/md-ingestion
- https://b2drop.eudat.eu/s/TmHbgdjbQnpAory
- https://www.bullsheet.de/S/OEP_-_B2FIND_mapping_nCHL6VNfF7X3
- https://github.com/trungdong/prov

**Comment by jh-RLI** [comment]
We Should use OMI to implement this.
