### ISSUE TITLE
Metadata spec is missing information on fields that are nullable

### ISSUE THREAD

**Issue by jh-RLI** [OpenEnergyPlatform/oemetadata#96]
To describe the table schema in the resource field, we need to add an option for nullable fields. As the schema field is also used for SQL table definitions, the nullable constraint is manadatory.

**Comment by Ludee** [comment]
I could not find any reference in the datapackage or other metadata standards.
This is a technical parameter for databases and thus can simply be added to each field.

`"nullable": false`

boolean
"badge": "Iron",
